Make xrange py3 compatible
In py3 ,
Xrange is renamed to range,
so it needs to be modified to make it compatible.
the code:
print (xrange(5))
Traceback (most recent call last):
  File "code", line 4, in <module>
    print (xrange(5))
NameError: name 'xrange' is not defined.
This patch will fix the issue.

Change-Id: Id7915878bd38b8e63aff2482e2272f1a0d9f4cfa
Closes-Bug: #1596127